name: CD - Deploy con Git Pull

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Crear clave SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H 137.184.127.11 >> ~/.ssh/known_hosts

      - name: Conectarse al servidor y hacer git pull
        run: |
          ssh alumno@137.184.127.11 "
            cd ~/lemp-sites/sebastian_maldonado &&
            git pull origin main
          "
