name: CD - Deploy con Git Pull

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Configurar clave SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 137.184.127.11 >> ~/.ssh/known_hosts

      - name: Hacer git pull en el servidor remoto
        run: |
          ssh -o StrictHostKeyChecking=no alumno@137.184.127.11 "
            cd ~/lemp-sites/sebastian_maldonado &&
            git pull origin main
          "

